name: Install Arch Distrobox on Ubuntu

on:
  push:
    branches:
      - main

jobs:
  install-arch-distrobox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Install Distrobox
        run: |
          curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh

      - name: Create Arch Distrobox
        run: |
          distrobox create --image archlinux --name arch -Y

      - name: Enter Arch Distrobox
        run: |
          distrobox enter arch -- sudo pacman -Syu neofetch arch-install-scripts archiso --noconfirm

      - name: Scaffhold archiso directory
        run: |
          distrobox enter arch -- cp -r /usr/share/archiso/configs/releng/ archlive
      
      - name: Configure archiso root user
        run: |
          echo "root:x:0:0:root:/root:/usr/bin/zsh" > archlive/airootfs/etc/passwd
      
      - name: Configure archiso root shadow
        run: |
          echo "root::14871::::::" > archlive/airootfs/etc/shadow
      
      - name: Configure archiso root group
        run: |
          echo "root:x:0:root" > archlive/airootfs/etc/group
      
      - name: Configure archiso root gshadow
        run: |
          echo "root:!*::root" > archlive/airootfs/etc/gshadow
      
      - name: Build archiso
        run: |
          sudo distrobox enter arch -- mkarchiso -v -w /tmp/archiso-tmp archlive
      
      - name: Make sure the archiso is here
        run: |
            ls -la
            ls -la out
