name: Install Arch Distrobox on Ubuntu

on:
  push:
    branches:
      - main

jobs:
  buildiso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Install Distrobox
        run: |
          curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh

      - name: Create Arch Distrobox
        run: |
          distrobox create --root --image archlinux --name arch -Y

      - name: Enter Arch Distrobox
        run: |
          distrobox enter --root arch -- sudo pacman -Syu neofetch arch-install-scripts archiso --noconfirm

      - name: Scaffhold archiso directory
        run: |
          distrobox enter --root arch -- cp -r /usr/share/archiso/configs/releng/ archlive
      
      - name: Configure archiso root user
        run: |
          echo "root:x:0:0:root:/root:/usr/bin/zsh" > archlive/airootfs/etc/passwd
          echo "liveuser:x:1000:1000::/home/liveuser:/usr/bin/zsh" >> archlive/airootfs/etc/passwd
      
      - name: Configure archiso root shadow
        run: |
          echo "root::14871::::::" > archlive/airootfs/etc/shadow
          echo "liveuser::14871::::::" >> archlive/airootfs/etc/shadow
      
      - name: Configure archiso root group
        run: |
          echo "root:x:0:root" > archlive/airootfs/etc/group
          echo "adm:x:4:liveuser" >> archlive/airootfs/etc/group
          echo "wheel:x:10:liveuser" >> archlive/airootfs/etc/group
          echo "uucp:x:14:liveuser" >> archlive/airootfs/etc/group
          echo "liveuser:x:1000:" >> archlive/airootfs/etc/group
      
      - name: Configure archiso root gshadow
        run: |
          echo "root:!*::root" > archlive/airootfs/etc/gshadow
          echo "liveuser:!*::" >> archlive/airootfs/etc/gshadow
      
      - name: Generate os-release
        run: |
          cat os-release > archlive/airootfs/etc/os-release
      
      - name: Patch profiledef.sh
        run: |
          python3 patch_profiledef.py
      
      - name: Add some dependencies
        run: |
          echo "hyprland" >> archlive/packages.x86_64
          echo "waybar" >> archlive/packages.x86_64
          echo "python" >> archlive/packages.x86_64
          echo "python-requests" >> archlive/packages.x86_64
          echo "python-systemd" >> archlive/packages.x86_64
          echo "npm" >> archlive/packages.x86_64
          echo "nodejs" >> archlive/packages.x86_64
          echo "electron33" >> archlive/packages.x86_64
      
      - name: Copy .config to archlive/airootfs/etc/skel
        run: |
          cp -r .config archlive/airootfs/etc/skel
      
      - name: Clone the installer
        run: |
          mkdir archlive/airootfs/opt
          mkdir archlive/airootfs/opt/installer
          git clone https://github.com/GMDProjectL/installer archlive/airoots/opt/installer
      
      - name: Build npm installer
        run: |
          cd archlive/airootfs/opt/installer
          npm install
          npm run build

      - name: Copy server systemd service from installer/assets/pgdl-server.service to /etc/systemd/system/pgdl-server.service
        run: |
          cp archlive/airootfs/opt/installer/assets/pgdl-server.service archlive/airootfs/etc/systemd/system/pgdl-server.service
      
      - name: Activate the service (it requires network-online.target)
        run: |
          ln -s /etc/systemd/system/pgdl-server.service archlive/airootfs/etc/systemd/system/multi-user.target.wants/pgdl-server.service
      
      - name: Build archiso
        run: |
          distrobox enter --root arch --root -- sudo mkarchiso -v -w builddir archlive
      
      - name: Install tree
        run: |
          sudo apt-get install tree
      
      #- name: Make sure the archiso is here
      #  run: |
      #      tree

      - name: Upload the ISO
        uses: actions/upload-artifact@v4
        with:
          path: out/*
